services:
  api:
    # Build image dari Dockerfile di direktori saat ini
    build: .
    # Nama container yang akan dibuat
    container_name: api-zte-status
    # Petakan port 8000 di host ke port 8000 di container
    ports:
      - "8000:8000"
    # Di sini Anda bisa mengatur environment variable untuk aplikasi
    environment:
      - SNMP_COMMUNITY_STRING=public
    # Atur agar container otomatis restart jika berhenti, kecuali dihentikan manual
    restart: unless-stopped

    # --- Opsi untuk Development (Live Reload) ---
    # Jika Anda ingin kode di-update secara otomatis saat ada perubahan,
    # hapus tanda pagar pada dua baris di bawah ini.
    # Ini akan me-mount kode lokal Anda ke dalam container dan menambahkan flag --reload.
    # volumes:
    #   - .:/app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
